import path from "node:path";
import fs from "node:fs";
import type { GenerationResult, ProjectManifest, ValidationReport } from "@image2roblox/schemas";
import { ensureDir, writeJsonFile, writeTextFile } from "@image2roblox/shared";

export interface RobloxGenerationInput {
  projectRoot: string;
  manifest: ProjectManifest;
  result: GenerationResult;
}

export interface RobloxGenerationOutput {
  requiredFiles: string[];
  writtenFiles: string[];
}

const REQUIRED_DIRS = [
  "source-image",
  "analysis",
  "roblox/src/ReplicatedStorage/Config",
  "roblox/src/ReplicatedStorage/Systems",
  "roblox/src/ServerScriptService",
  "roblox/src/StarterPlayer/StarterPlayerScripts",
  "roblox/src/StarterGui",
  "roblox/src/Workspace",
  "roblox/src/Lighting",
  "roblox/src/SoundService",
  "exports",
  "logs"
];

const REQUIRED_FILES = [
  "analysis/image-analysis.json",
  "analysis/world-bible.md",
  "analysis/gameplay-plan.json",
  "analysis/build-plan.json",
  "roblox/default.project.json",
  "roblox/src/ReplicatedStorage/Config/WorldConfig.luau",
  "roblox/src/ReplicatedStorage/Config/BuildPlanConfig.luau",
  "roblox/src/ReplicatedStorage/Systems/QuestTracker.luau",
  "roblox/src/ReplicatedStorage/Systems/TriggerZones.luau",
  "roblox/src/ServerScriptService/Main.server.luau",
  "roblox/src/ServerScriptService/CollectibleService.server.luau",
  "roblox/src/ServerScriptService/CheckpointService.server.luau",
  "roblox/src/ServerScriptService/InteractPromptService.server.luau",
  "roblox/src/ServerScriptService/DamageZoneService.server.luau",
  "roblox/src/ServerScriptService/NPCDialogService.server.luau",
  "roblox/src/ServerScriptService/EnemyPlaceholderAI.server.luau",
  "roblox/src/StarterPlayer/StarterPlayerScripts/HUD.client.luau",
  "roblox/src/Workspace/Blockout.server.luau",
  "roblox/src/Lighting/LightingConfig.luau",
  "roblox/src/SoundService/SoundPlan.luau",
  "README.md"
];

function formatWorldBibleMarkdown(result: GenerationResult): string {
  const { worldBible } = result;
  const poiLines = worldBible.pointsOfInterest
    .map((poi) => `- **${poi.name}** (${poi.riskLevel}) - ${poi.purpose}. ${poi.traversalNotes}`)
    .join("\n");
  const zoneLines = worldBible.zones.map((zone) => `- **${zone.name}** - ${zone.description} (${zone.traversalStyle})`).join("\n");

  return `# ${worldBible.theme}

## World Summary
${worldBible.worldSummary}

## Setting
${worldBible.setting}

## Tone
${worldBible.tone}

## Lore Seed
${worldBible.loreSeed}

## Main Landmark
${worldBible.mainLandmark}

## Main Objective
${worldBible.mainObjective}

## Zones
${zoneLines}

## Points of Interest
${poiLines}

## Environmental Storytelling
${worldBible.environmentalStorytelling.map((item) => `- ${item}`).join("\n")}

## Weather and Time
- Weather: ${worldBible.weatherDirection}
- Day/Night: ${worldBible.dayNightDirection}

## Soundscape
${worldBible.soundscape}
`;
}

function createRojoProjectJson(manifest: ProjectManifest): unknown {
  return {
    name: `${manifest.slug}-game`,
    tree: {
      $className: "DataModel",
      ReplicatedStorage: {
        $path: "src/ReplicatedStorage"
      },
      ServerScriptService: {
        $path: "src/ServerScriptService"
      },
      StarterPlayer: {
        $path: "src/StarterPlayer"
      },
      StarterGui: {
        $path: "src/StarterGui"
      },
      Workspace: {
        $path: "src/Workspace"
      },
      Lighting: {
        $path: "src/Lighting"
      },
      SoundService: {
        $path: "src/SoundService"
      }
    }
  };
}

function luauModule(name: string, body: string): string {
  return `--!strict\n-- Generated by Image2Roblox Builder\n-- Module: ${name}\n\n${body}\n`;
}

function writeRobloxScripts(root: string, result: GenerationResult): void {
  writeTextFile(
    path.join(root, "roblox/src/ReplicatedStorage/Config/WorldConfig.luau"),
    luauModule(
      "WorldConfig",
      `local WorldConfig = {\n  theme = ${JSON.stringify(result.worldBible.theme)},\n  biome = ${JSON.stringify(
        result.imageAnalysis.biome
      )},\n  mood = ${JSON.stringify(result.imageAnalysis.mood)},\n  primaryGameplay = ${JSON.stringify(
        result.gameplayPlan.primaryGameplayType
      )},\n  mainObjective = ${JSON.stringify(result.gameplayPlan.mainObjective)},\n  collectiblesTarget = ${result.gameplayPlan.collectibles.length},\n}\n\nreturn WorldConfig`
    )
  );

  writeTextFile(
    path.join(root, "roblox/src/ReplicatedStorage/Config/BuildPlanConfig.luau"),
    luauModule(
      "BuildPlanConfig",
      `local BuildPlanConfig = {\n  structures = ${JSON.stringify(result.buildPlan.structureList)},\n  hazards = ${JSON.stringify(
        result.buildPlan.hazards
      )},\n  checkpoints = ${JSON.stringify(result.buildPlan.checkpoints)},\n}\n\nreturn BuildPlanConfig`
    )
  );

  writeTextFile(
    path.join(root, "roblox/src/ReplicatedStorage/Systems/QuestTracker.luau"),
    luauModule(
      "QuestTracker",
      "local QuestTracker = {}\n\nfunction QuestTracker.new(targetCount)\n  return { current = 0, target = targetCount }\nend\n\nfunction QuestTracker.addProgress(state, amount)\n  state.current += amount\n  if state.current > state.target then\n    state.current = state.target\n  end\n  return state.current, state.target\nend\n\nreturn QuestTracker"
    )
  );

  writeTextFile(
    path.join(root, "roblox/src/ReplicatedStorage/Systems/TriggerZones.luau"),
    luauModule(
      "TriggerZones",
      "local TriggerZones = {}\n\nfunction TriggerZones.bind(part, callback)\n  part.Touched:Connect(function(hit)\n    callback(hit)\n  end)\nend\n\nreturn TriggerZones"
    )
  );

  writeTextFile(
    path.join(root, "roblox/src/ServerScriptService/Main.server.luau"),
    `--!strict
-- Generated by Image2Roblox Builder
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Players = game:GetService("Players")

local WorldConfig = require(ReplicatedStorage.Config.WorldConfig)
local QuestTracker = require(ReplicatedStorage.Systems.QuestTracker)

local playerStates: { [Player]: { current: number, target: number } } = {}

Players.PlayerAdded:Connect(function(player)
  playerStates[player] = QuestTracker.new(WorldConfig.collectiblesTarget)
end)

Players.PlayerRemoving:Connect(function(player)
  playerStates[player] = nil
end)

print("Image2Roblox generated server bootstrap started for", WorldConfig.theme)
`
  );

  writeTextFile(
    path.join(root, "roblox/src/ServerScriptService/CollectibleService.server.luau"),
    `--!strict
local CollectionService = game:GetService("CollectionService")

for _, collectible in CollectionService:GetTagged("Collectible") do
  collectible.Touched:Connect(function(hit)
    local character = hit.Parent
    if character and character:FindFirstChild("Humanoid") then
      collectible:Destroy()
    end
  end)
end
`
  );

  writeTextFile(
    path.join(root, "roblox/src/ServerScriptService/CheckpointService.server.luau"),
    `--!strict
local CollectionService = game:GetService("CollectionService")

for _, checkpoint in CollectionService:GetTagged("Checkpoint") do
  checkpoint.Touched:Connect(function(hit)
    local character = hit.Parent
    if character and character:FindFirstChild("Humanoid") then
      print("Checkpoint reached:", checkpoint.Name)
    end
  end)
end
`
  );

  writeTextFile(
    path.join(root, "roblox/src/ServerScriptService/InteractPromptService.server.luau"),
    `--!strict
local CollectionService = game:GetService("CollectionService")

for _, interactable in CollectionService:GetTagged("Interactable") do
  local prompt = interactable:FindFirstChildOfClass("ProximityPrompt")
  if prompt then
    prompt.Triggered:Connect(function(player)
      print("Interact triggered", interactable.Name, "by", player.Name)
    end)
  end
end
`
  );

  writeTextFile(
    path.join(root, "roblox/src/ServerScriptService/DamageZoneService.server.luau"),
    `--!strict
local CollectionService = game:GetService("CollectionService")

for _, zone in CollectionService:GetTagged("DamageZone") do
  zone.Touched:Connect(function(hit)
    local humanoid = hit.Parent and hit.Parent:FindFirstChildOfClass("Humanoid")
    if humanoid then
      humanoid:TakeDamage(8)
    end
  end)
end
`
  );

  writeTextFile(
    path.join(root, "roblox/src/ServerScriptService/NPCDialogService.server.luau"),
    `--!strict
local dialogLines = {
  ${result.gameplayPlan.npcDialogHooks.map((line) => JSON.stringify(line)).join(",\n  ")}
}

print("NPC dialog hooks loaded", #dialogLines)
`
  );

  writeTextFile(
    path.join(root, "roblox/src/ServerScriptService/EnemyPlaceholderAI.server.luau"),
    `--!strict
local RunService = game:GetService("RunService")

RunService.Heartbeat:Connect(function()
  -- Placeholder: replace with pathfinding and attack state machine
end)
`
  );

  writeTextFile(
    path.join(root, "roblox/src/StarterPlayer/StarterPlayerScripts/HUD.client.luau"),
    `--!strict
local Players = game:GetService("Players")
local player = Players.LocalPlayer

print("HUD initialized for", player.Name)
-- Placeholder HUD binding for objective, collectibles, and health
`
  );

  writeTextFile(
    path.join(root, "roblox/src/Workspace/Blockout.server.luau"),
    `--!strict
local Workspace = game:GetService("Workspace")

local function createPlatform(name: string, position: Vector3, size: Vector3, color: Color3)
  local part = Instance.new("Part")
  part.Name = name
  part.Anchored = true
  part.Size = size
  part.Position = position
  part.Color = color
  part.Parent = Workspace
  return part
end

createPlatform("SpawnHub", Vector3.new(0, 5, 0), Vector3.new(80, 1, 80), Color3.fromRGB(110, 150, 180))
createPlatform("LandmarkPlateau", Vector3.new(0, 25, -220), Vector3.new(120, 2, 120), Color3.fromRGB(140, 120, 120))
createPlatform("HazardBridge", Vector3.new(0, 10, -100), Vector3.new(20, 1, 160), Color3.fromRGB(180, 80, 80))
`
  );

  writeTextFile(
    path.join(root, "roblox/src/Lighting/LightingConfig.luau"),
    luauModule(
      "LightingConfig",
      `local LightingConfig = {\n  brightness = ${result.buildPlan.lightingSettings.brightness},\n  clockTime = ${result.buildPlan.lightingSettings.clockTime},\n  fogColor = ${JSON.stringify(
        result.buildPlan.lightingSettings.fogColor
      )},\n  fogEnd = ${result.buildPlan.lightingSettings.fogEnd},\n  atmosphereDensity = ${result.buildPlan.lightingSettings.atmosphereDensity},\n}\n\nreturn LightingConfig`
    )
  );

  writeTextFile(
    path.join(root, "roblox/src/SoundService/SoundPlan.luau"),
    luauModule(
      "SoundPlan",
      `local SoundPlan = {\n  cues = ${JSON.stringify(result.buildPlan.soundPlan)}\n}\n\nreturn SoundPlan`
    )
  );
}

function writeProjectReadme(root: string, manifest: ProjectManifest, result: GenerationResult): void {
  const readme = `# ${manifest.name}

Generated by Image2Roblox Builder.

## What was generated

- Theme: ${result.worldBible.theme}
- Main Landmark: ${result.worldBible.mainLandmark}
- Main Objective: ${result.worldBible.mainObjective}
- Primary Gameplay: ${result.gameplayPlan.primaryGameplayType}

## Import into Roblox Studio

1. Open Roblox Studio and create a new place.
2. Install Rojo if not already installed.
3. In this folder, run Rojo serve against \`roblox/default.project.json\`.
4. Connect Studio Rojo plugin to sync generated files.
5. Run the game and iterate on blockout and systems.

## Notes

- Scripts are starter-grade and intentionally modular.
- Placeholder assets are used where image certainty is low.
- Generated outputs can be safely edited by hand.
`;
  writeTextFile(path.join(root, "README.md"), readme);
}

export function generateRobloxProject(input: RobloxGenerationInput): RobloxGenerationOutput {
  const writtenFiles: string[] = [];

  for (const relativeDir of REQUIRED_DIRS) {
    ensureDir(path.join(input.projectRoot, relativeDir));
  }

  writeJsonFile(path.join(input.projectRoot, "analysis/image-analysis.json"), input.result.imageAnalysis);
  writtenFiles.push("analysis/image-analysis.json");

  writeTextFile(path.join(input.projectRoot, "analysis/world-bible.md"), formatWorldBibleMarkdown(input.result));
  writtenFiles.push("analysis/world-bible.md");

  writeJsonFile(path.join(input.projectRoot, "analysis/gameplay-plan.json"), input.result.gameplayPlan);
  writtenFiles.push("analysis/gameplay-plan.json");

  writeJsonFile(path.join(input.projectRoot, "analysis/build-plan.json"), input.result.buildPlan);
  writtenFiles.push("analysis/build-plan.json");

  writeJsonFile(path.join(input.projectRoot, "roblox/default.project.json"), createRojoProjectJson(input.manifest));
  writtenFiles.push("roblox/default.project.json");

  writeRobloxScripts(input.projectRoot, input.result);
  writtenFiles.push(...REQUIRED_FILES.filter((file) => file.endsWith(".luau") || file.includes("server.luau") || file.includes("client.luau")));

  ensureDir(path.join(input.projectRoot, "exports"));
  ensureDir(path.join(input.projectRoot, "logs"));

  writeProjectReadme(input.projectRoot, input.manifest, input.result);
  writtenFiles.push("README.md");

  return {
    requiredFiles: REQUIRED_FILES,
    writtenFiles
  };
}

export function validateGeneratedOutput(projectRoot: string): ValidationReport {
  const checks: ValidationReport["checks"] = [];
  const missingFiles: string[] = [];

  for (const relativeFile of REQUIRED_FILES) {
    const absolute = path.join(projectRoot, relativeFile);
    const exists = fs.existsSync(absolute);
    checks.push({
      id: `required:${relativeFile}`,
      name: `Required output ${relativeFile}`,
      status: exists ? "pass" : "fail",
      details: exists ? "Found" : "Missing"
    });
    if (!exists) {
      missingFiles.push(relativeFile);
    }
  }

  return {
    generatedAt: new Date().toISOString(),
    checks,
    errors: [],
    warnings: [],
    missingFiles,
    confidenceSummary: {
      min: 0.7,
      max: 0.85,
      average: 0.77
    },
    nextActions:
      missingFiles.length > 0
        ? ["Run Build Roblox Project again to complete missing files."]
        : ["Open roblox/default.project.json with Rojo and sync to Studio."],
    isValid: missingFiles.length === 0
  };
}
